### ISSUE TITLE
Error when trying to run Maid

### ISSUE THREAD

**Issue by bighungry** [maid/maid#289] opened 2023-04-13 16:50 UTC
I'm running Pop_OS! 22.04 and I get this error with ruby 2.7 and ruby 3.0.

When running maid, this error is generated:

```
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': /var/lib/gems/3.0.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: _1 is reserved for numbered parameter (SyntaxError)
/var/lib/gems/3.0.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: _2 is reserved for numbered parameter
/var/lib/gems/3.0.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: _3 is reserved for numbered parameter
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/mime-types-2.99.3/lib/mime/types/deprecations.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/mime-types-2.99.3/lib/mime/types.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/maid-0.7.0/lib/maid/tools.rb:8:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/maid-0.7.0/lib/maid.rb:7:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/maid-0.7.0/bin/maid:3:in `<top (required)>'
	from /usr/local/bin/maid:25:in `load'
	from /usr/local/bin/maid:25:in `<main>'
```

**Comment by benjaminoakes** [comment] 2023-04-15 22:38
Thanks for reporting this!

Could you please share any rules that led to this error and any other details to reproduce the issue?  If you're experienced enough to be able to make a pull request that includes a failing test, that would be very helpful as well.

**Comment by benjaminoakes** [comment] 2023-04-15 22:40
Please also note that you will need to run a pre-release version for Ruby 3.0 support.  Please consider testing a version newer than v0.7.0 and report whether that resolves your issue.

**Comment by coaxial** [comment] 2023-04-18 12:01
@bighungry 0.7.0 isn't compatible with Ruby > 2.6, and Ruby 2.6 is a pain to install because it depends on outdated openssl that Linux distros don't ship anymore.

You should run 0.10.0 instead with `bundle install maid --pre` which is compatible with 2.7 and above.

Closing for now, feel free to re-open if you still have issues with 0.10.0 and Ruby 2.7+

**Closed by coaxial** 2023-04-18 12:01 UTC
