### ISSUE TITLE
move() exception when running as a daemon

### ISSUE THREAD

**Issue by fortinmike** [maid/maid#159] opened 2016-07-12 13:27 UTC
Somehow the Maid daemon crashes at startup when I use the move tool in a simple watch rule. Any idea why this occurs and what I could do to work around this?

**Conditions:**

Ruby 2.3.1 (installed with Homebrew)

``` ruby
watch "Move screenshots" do
    destination = "~/Pictures/Screen Shots/"
    dir("~/Desktop/Screen Shot *").each do |path|
      move(path, destination)
    end
end
```
- The daemon crashes _only_ when there is already a screen shot on the desktop when it's started
- If the daemon is started while there is no screenshot on the desktop, it starts successfully but doesn't seem to watch the folder for changes (dropping a screenshot on the desktop does nothing)
- Replacing `watch` with `rule` and running `maid clean --force` does the expected thing (moves the screenshot in the `~/Pictures/Screen Shots/` directory.

**Stack trace:**

``` shell
~ maid daemon
Logging actions to "/Users/Michael/.maid/maid.log"
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1599:in `dup': can't dup NilClass (TypeError)
    from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:1599:in `fu_check_options'
    from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/fileutils.rb:514:in `mv'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/tools.rb:45:in `block in move'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/tools.rb:43:in `each'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/tools.rb:43:in `move'
    from /Users/Michael/.maid/rules.rb:14:in `block (3 levels) in <top (required)>'
    from /Users/Michael/.maid/rules.rb:13:in `each'
    from /Users/Michael/.maid/rules.rb:13:in `block (2 levels) in <top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/rule_container.rb:8:in `instance_exec'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/rule_container.rb:8:in `initialize_rules'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/watch.rb:12:in `initialize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/maid.rb:89:in `new'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/maid.rb:89:in `watch'
    from /Users/Michael/.maid/rules.rb:11:in `block in <top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid.rb:35:in `instance_exec'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid.rb:35:in `rules'
    from /Users/Michael/.maid/rules.rb:10:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/maid.rb:82:in `load'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/maid.rb:82:in `block in load_rules'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid.rb:28:in `with_instance'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/maid.rb:78:in `load_rules'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/lib/maid/app.rb:92:in `daemon'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /usr/local/lib/ruby/gems/2.3.0/gems/maid-0.7.0/bin/maid:5:in `<top (required)>'
    from /usr/local/bin/maid:23:in `load'
    from /usr/local/bin/maid:23:in `<main>'
```

**Comment by benjaminoakes** [comment] 2016-07-14 02:47
This could maybe use better messaging... The `watch` command takes a path, not a description. See the README for an example.

I'd happily accept a PR that gives a more obvious warning, assuming that's the root cause.

**Comment by fortinmike** [comment] 2016-07-14 17:50
Oh right! How did I miss this...

I can't guarantee I'll find the time, but what would an acceptable PR look like for this possible check? Maybe the watch tool could make sure the string is a path, that it exists on the filesystem, and throw with a helpful message otherwise?

**Comment by benjaminoakes** [comment] 2016-07-14 18:00
> Maybe the watch tool could make sure the string is a path, that it exists on the filesystem, and throw with a helpful message otherwise?

Yup, that's what I was thinking.  Something like:

```ruby
if !File.exist?(expand(path_that_watch_received))
  raise 'helpful error message'
end
```

**Comment by coaxial** [comment] 2023-04-01 09:00
Closing in favor of #282

**Closed by coaxial** 2023-04-01 09:00 UTC
Labels: improvement
